name: Go
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.12
        uses: actions/setup-go@v1
        with:
          go-version: 1.12
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Download linter
        run: |
          curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.17.1

      - name: Get dependencies
        run: |
          go mod download

      - name: Lint
        run: |
          golangci-lint run

      - name: Test
        rune: |
          go test -v -race ./...

      - name: Build
        run: go build -v .
